development:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") %>
      options:
        server_selection_timeout: 5000
test:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") %>
      options:
        server_selection_timeout: 5000
production:
  clients:
    default:
      uri: <%= ENV.fetch("MONGODB_URI") %>
      options:
        server_selection_timeout: 5000